version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    container_name: redis
    networks:
      - database

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookvita
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - database

  server:
    build: ./server/
    networks:
      - database
      - web
    depends_on:
        - postgres
        - redis
    environment:
        DB_HOST: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: bookvita
        DB_PORT: 5432
        REDIS_URL: redis://redis:6379
        DJANGO_SETTINGS_MODULE: server.settings_prod
        ALLOWED_HOSTS: 'server'

  client:
    build: ./client/
    ports:
      - "5173:5173"

    networks:
        - web

    depends_on:
        - server
        - redis
        - postgres
    environment:
      SERVER_URL: http://server:8000

networks:
    database:
        driver: bridge
    web:
        driver: bridge