# Generated by Django 4.2 on 2023-05-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='track',
        ),
    ]
