# Generated by Django 4.2 on 2023-04-29 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelves',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookshelvelikes',
            name='book_shelve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelve_likes', to='bookshelves.bookshelves'),
        ),
        migrations.AddField(
            model_name='bookshelvelikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelve_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookshelvebooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelve_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookshelvebooks',
            name='book_shelve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelve_books', to='bookshelves.bookshelves'),
        ),
    ]
