# Generated by Django 4.2 on 2023-04-29 11:03

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('author_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('author_url', models.CharField(blank=True, max_length=255, null=True)),
                ('author_info', models.TextField(blank=True, max_length=2000, null=True)),
                ('author_image_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('cover_id', models.IntegerField(blank=True, null=True)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None)),
                ('rating_count', models.IntegerField(blank=True, default=0, null=True)),
                ('average_rating', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('book_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='BookLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'db_table': 'book_likes',
            },
        ),
    ]
