# Generated by Django 4.2 on 2023-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_ol_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
