# Generated by Django 4.2 on 2023-04-20 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None),
        ),
    ]
