# Generated by Django 4.2 on 2023-04-30 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_ol_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booklikes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
